/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>

//RCC configuration
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t*)(RCC_BASE + 0x18)

//GPIO configuration
#define GPIOA_BASE 0x40010800
#define GPIO_CRH  *(volatile uint32_t*)(GPIOA_BASE + 0x04)
#define GPIO_ODR  *(volatile uint32_t*)(GPIOA_BASE + 0x0C)
#define GPIOx_CRL *(volatile uint32_t*)(GPIOA_BASE + 0x08)


//AFIO configuration
#define AFIO_BASE 0x40010800
#define AFIO_EXTICR1 *(volatile uint32_t*)(AFIO_BASE + 0x08)


//Interrupt configuration
#define EXTI_Base 0x40010400
#define EXTI_IMR  *(volatile uint32_t*)(EXTI_Base + 0x00)
#define EXTI_RTSR *(volatile uint32_t*)(EXTI_Base + 0x08)
#define EXTI_PR   *(volatile uint32_t*)(EXTI_Base + 0x14)
#define NVIC_ISER0 *(volatile uint32_t*)(0xE000E100)



void RCC_init(void)
{
	RCC_APB2ENR |= (1<<2) ;
	RCC_APB2ENR |= (1<<0) ;

}
void GPIOA_init(void)
{

	GPIO_CRH  &= 0xff0fffff ;
	GPIO_CRH  |= 0x00200000 ;
	GPIOx_CRL |=(1<<1);

}
void EXTI_init(void)
{

	EXTI_IMR   |= (1<<0) ;
	EXTI_RTSR  |= (1<<0) ;
}

void EXTI0_IRQHandler(void)
{
	GPIO_ODR |=(1<<13);
	EXTI_PR  |=(1<<0) ;
}
void AFIO_init(void)
{

	AFIO_EXTICR1  =0 ;

}



int main(void)
{
    /* Loop forever */
	RCC_init();
	GPIOA_init();
	AFIO_init();
	EXTI_init();
	EXTI0_IRQHandler();
	NVIC_ISER0 |=(1<<6);
	for(;;);



}
